------ 시스템 계정
--CREATE USER C##ZOODY IDENTIFIED BY 1234;
------ 권한부여
--GRANT CONNECT , RESOURCE TO C##ZOODY;
------ 테이블스페이스 권한 수정
--ALTER USER C##ZOODY DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

